#pragma once

#define BROADCAST_NODE_ANNOUNCE_SIZE 3
#define BROADCAST_RTS_SIZE 8
#define BROADCAST_CONTINUOUS_RTS_SIZE 6
#define BROADCAST_CTS_SIZE 4
#define BROADCAST_FRAGMENT_METADATA_SIZE 5
#define BROADCAST_LEADER_FRAGMENT_METADATA_SIZE 7

#define LORA_MAX_PACKET_SIZE 255
#define LORA_MAX_FRAGMENT_PAYLOAD 250
#define LORA_MAX_FRAGMENT_LEADER_PAYLOAD 248

#define MAX_PACKET_TIME 210

#define MESSAGE_TYPE_BROADCAST_CONFIG 0x00
#define MESSAGE_TYPE_BROADCAST_NODE_ANNOUNCE 0x01
#define MESSAGE_TYPE_BROADCAST_RTS 0x02
#define MESSAGE_TYPE_BROADCAST_CONTINUOUS_RTS 0x03
#define MESSAGE_TYPE_BROADCAST_CTS 0x04
#define MESSAGE_TYPE_BROADCAST_LEADER_FRAGMENT 0x05
#define MESSAGE_TYPE_BROADCAST_FRAGMENT 0x06

#define TOPOLOGY_FULLY_MESHED 0
#define TOPOLOGY_LINE 1
#define TOPOLOGY_COMPLEX 2
#define MAX_NETWORK_ID 3
#define MAX_NUMBER_OF_NODES 8

inline constexpr uint8_t allNodeIds[] = { 32, 92, 4, 100, 52, 104, 248, 16 };
